services:
  # The server handling login callback requests.
  tobira-login-handler:
    image: node:18
    ports:
      - "3091:3091"
    volumes:
      - ../dummy-login/dist/index.js:/usr/bin/login-handler.js
    command: node /usr/bin/login-handler.js

  # A reverse proxy in front of Opencast that just adds some CORS headers
  # (required for the Tobira uploader, for example).
  opencast-cors-proxy:
    image: nginx
    ports:
      - "8081:8081"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./opencast-cors-proxy-nginx.conf:/etc/nginx/conf.d/default.conf

  # A PostgreSQL database for Tobira.
  tobira-dev-database:
    image: docker.io/yugabytedb/yugabyte:2025.2.2.1-b1
    restart: unless-stopped
    command:
      - "bin/yugabyted"
      - "start"
      - "--tserver_flags=allowed_preview_flags_csv=ysql_yb_ddl_transaction_block_enabled,ysql_yb_ddl_transaction_block_enabled=true,enable_object_locking_for_table_locks=true"
      - "--background=false"
    ports:
      - 127.0.0.1:7001:7000   # cluster management
      - 127.0.0.1:9000:9000   # node management
      - 127.0.0.1:15433:15433 # metrics
      - 127.0.0.1:5433:5433   # YSQL
      - 127.0.0.1:9042:9042   # YCQL
    volumes:
      - tobira-dev-postgres:/root/var/data
    environment:
      - YSQL_PASSWORD=tobira
      - YSQL_USER=tobira
      - YSQL_DB=tobira

  # A MeiliSearch for Tobira.
  tobira-meilisearch:
    image: getmeili/meilisearch:v1.12
    restart: unless-stopped
    ports:
      - 127.0.0.1:7700:7700
    volumes:
      - tobira-dev-meili:/data.ms
    environment:
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=tobira

  # A static file server for UI tests
  tobira-ui-test-files:
    image: nginx
    ports:
      - "38456:38456"
    volumes:
      - ./ui-test-files-nginx.conf:/etc/nginx/conf.d/default.conf
      - ./test-files:/www/data


volumes:
  tobira-dev-postgres:
  tobira-dev-meili:
